customer/urls.py
from django.conf.urls import include, url
from customer import views
urlpatterns = [
    #for sale
    url(r'^customerManage$', views.customerManage, name='customerManage'),
    url(r'^queryCustomer$', views.queryCustomer, name='queryCustomer'),
    url(r'^addCustomer$', views.addCustomer, name='addCustomer'),
    url(r'^delCustomer$', views.delCustomer, name='delCustomer'),
    url(r'^delCustomerBySale$', views.delCustomerBySale, name='delCustomerBySale'),
    url(r'^checkCustomerPhone$', views.checkCustomerPhone, name='checkCustomerPhone'),
    url(r'^checkCustomerPhoneForEdit$', views.checkCustomerPhoneForEdit, name='checkCustomerPhoneForEdit'),

    #for teacher
    url(r'^customerHandle$', views.customerHandle, name='customerHandle'),
    url(r'^queryCustomerHandle$', views.queryCustomerHandle, name='queryCustomerHandle'),
    url(r'^handleCustomer$', views.handleCustomer, name='handleCustomer'),
    url(r'^handleValidCustomer$', views.handleValidCustomer, name='handleValidCustomer'),
    url(r'^handleValidCustomer$', views.handleValidCustomer, name='handleValidCustomer'),
    url(r'^editSpot$', views.editSpot, name='editSpot'),
    url(r'^handleSpotCustomer$', views.handleSpotCustomer, name='handleSpotCustomer'),
    url(r'^addTeacherCustomer$', views.addTeacherCustomer, name='addTeacherCustomer'),

    #for bursar
    url(r'^customerPay$', views.customerPay, name='customerPay'),
    url(r'^queryCustomerPay$', views.queryCustomerPay, name='queryCustomerPay'),
    url(r'^tradePayManage$', views.tradePayManage, name='tradePayManage'),
    url(r'^queryTradePayManage$', views.queryTradePayManage, name='queryTradePayManage'),

    #for trade
    url(r'^getCustomerById$', views.getCustomerById, name='getCustomerById'),
    url(r'^getSpotCustomerById$', views.getSpotCustomerById, name='getSpotCustomerById'),

    #for report
    url(r'^noTradeCustomerReport$', views.noTradeCustomerReport, name='noTradeCustomerReport'),
    url(r'^tradeTypeReport$', views.tradeTypeReport, name='tradeTypeReport'),
    url(r'^getTeacherDetail$', views.getTeacherDetail, name='getTeacherDetail'),
    url(r'^getStockDetail$', views.getStockDetail, name='getStockDetail'),
    url(r'^dCustomerReport$', views.dCustomerReport, name='dCustomerReport'),
    url(r'^analyzeReport$', views.analyzeReport, name='analyzeReport'),
    url(r'^queryAnalyzeReport$', views.queryAnalyzeReport, name='queryAnalyzeReport'),
    url(r'^sortAnalyzeReport$', views.sortAnalyzeReport, name='sortAnalyzeReport'),
    url(r'^getStockDetailForAnalyze$', views.getStockDetailForAnalyze, name='getStockDetailForAnalyze'),
    url(r'^calcProfitByStockId$', views.calcProfitByStockId, name='calcProfitByStockId'),
    url(r'^resumeDishonestCustomer$', views.resumeDishonestCustomer, name='resumeDishonestCustomer'),



]

ops/urls.py
from django.conf.urls import include, url
from ops import views
urlpatterns = [
    url(r'^userManage$', views.userManage, name='userManage'),
    url(r'^addUser$', views.addUser, name='addUser'),
    url(r'^queryUser$', views.queryUser, name='queryUser'),
    url(r'^delUser$', views.delUser, name='delUser'),
    url(r'^resetPw$', views.resetPw, name='resetPw'),
    url(r'^chargebackSerial$', views.chargebackSerial, name='chargebackSerial'),
    url(r'^checkUserId$', views.checkUserId, name='checkUserId'),
    url(r'^checkEditUserId$', views.checkEditUserId, name='checkEditUserId'),
    url(r'^checkCId$', views.checkCId, name='checkCId'),
    url(r'^checkEditCId$', views.checkEditCId, name='checkEditCId'),
    url(r'^systermLog$', views.systemLog, name='systemLog'),
    url(r'^addFixContent$',views.addFixContent,name='addFixContent'),
    url(r'^queryLog$',views.queryLog,name='queryLog'),
]

shande/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from super import urls as superurls
from ops import urls as opsurls
from sale import urls as saleurls
from customer import urls as customerurls
from teacher import urls as teacherurls
from bursar import urls as bursarurls
from wxqq import urls as wxqqurls
from trade import urls as tradeurls
from spot import urls as spoturls
from stock import urls as stockurls
from analyst import urls as analysturls
from shande.settings import STATIC_ROOT
urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # app super [default]
    url(r'', include(superurls, namespace="super")),

    # app ops
    url(r'^ops/', include(opsurls, namespace="ops")),

    # app sale
    url(r'^sale/', include(saleurls, namespace="sale")),

    # app customer
    url(r'^customer/', include(customerurls, namespace="customer")),

    # app teacher
    url(r'^teacher/', include(teacherurls, namespace="teacher")),

    # app bursar
    url(r'^bursar/', include(bursarurls, namespace="bursar")),

    # app wxqq
    url(r'^wxqq/', include(wxqqurls, namespace="wxqq")),

    # app trade
    url(r'^trade/', include(tradeurls, namespace="trade")),

    # app spot
    url(r'^spot/', include(spoturls, namespace="spot")),

    # app stock
    url(r'^stock/', include(stockurls, namespace="stock")),

    # app analyst
    url(r'^analyst/', include(analysturls, namespace="analyst")),
]
#
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG is False:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.UPLOAD_ROOT)
#     urlpatterns.append(url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),)

trade/urls.py
from django.conf.urls import include, url
from trade import views
urlpatterns = [
    url(r'^queryTrade$', views.queryTrade, name='queryTrade'),
    url(r'^getNameByStockId$', views.getNameByStockId, name='getNameByStockId'),

    # for teacher
    url(r'^tradeManage$', views.tradeManage, name='tradeManage'),
    url(r'^addTrade$', views.addTrade, name='addTrade'),
    url(r'^handleTrade$', views.handleTrade, name='handleTrade'),
    url(r'^deleteTrade$', views.deleteTrade, name='deleteTrade'),
    url(r'^updateFile$', views.updateFile, name='updateFile'),
    url(r'^showFile$', views.showFile, name='showFile'),

    # for bursar
    url(r'^payManage$', views.payManage, name='payManage'),
    url(r'^payTrade$', views.payTrade, name='payTrade'),
    url(r'^backTrade$', views.backTrade, name='backTrade'),
    url(r'^backTradeAdmin$', views.backTradeAdmin, name='backTradeAdmin'),
]

trade/views.py
# coding=utf-8
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.db.models import Q
from django.utils import timezone

import os
import random
import string
import datetime
import traceback
import json

from shande.settings import BASE_DIR, UPLOAD_ROOT
from shande.util import *
from ops.models import *
from super.models import *
from sale.models import *
from customer.models import *
from trade.models import *
from analyst.models import *
import logging
logger = logging.getLogger("django")

@login_required()
def tradeManage(request):

    if (not request.user.userprofile.title.role_name in ['admin', 'ops', 'teacher', 'teachermanager', 'teacherboss']):
        return HttpResponseRedirect("/")
    customerId = request.GET.get("customerId")
    customer = Customer.objects.get(id=customerId)
    bursars = Bursar.objects.all().order_by("bursarId")
    analysts = Analyst.objects.filter(company=request.user.userprofile.company)
    # analysts = Analyst.objects.all()
    # bursarId = []
    # bursarNick = []
    # for bursar in bursars:
    #      bursarId.append(bursar.bursarId)
    #      bursarNick.append(bursar.binduser.userprofile.nick)
    #
    # json_bursarId = json.dumps(bursarId)
    # json_bursarNick = json.dumps(bursarNick)

    data = {
        "customer": customer,
        "bursars": bursars,
        "analysts": analysts,
        # "json_bursarId": json_bursarId,
        # "json_bursarNick": json_bursarNick,
    }

    return render(request, 'trade/tradeManage.html', data)

@login_required()
def queryTrade(request):
    customerId = request.GET.get("customerid")
    trades = Trade.objects.filter(customer_id=customerId)
    user = request.user
    user_title = user.userprofile.title
    # 分页
    p = Paginator(trades, 20)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        tradePage = p.page(page)
    except (EmptyPage, InvalidPage):
        tradePage = p.page(p.num_pages)
    data = {
        "tradePage": tradePage,
        "requestArgs": getArgsExcludePage(request),
        "user_title": user_title,
    }
    return render(request, 'trade/queryTrade.html', data)

@login_required()
def addTrade(request):

    data = {}
    firstTrade = False
    secondTrade = False
    buyprice = float(request.POST.get('buyprice'))
    buycount = int(request.POST.get('buycount'))
    buycash = buyprice * buycount
    analystId = request.POST.get('analystid')

    try:
        if float(request.POST.get('buycount')) == 0:
            raise Exception("buycountzero")
        customer = Customer.objects.get(id=request.POST.get('customerid'))
        # 判断是否首笔交易
        existTrade = Trade.objects.filter(customer=customer).count()
        # if existTrade.__len__() == 0:
        if existTrade == 0:
            firstTrade = True
            if buycash < 20000:
                raise Exception("buycashlow")
        # elif existTrade.__len__() == 1:
        elif existTrade == 1:
            secondTrade = True


        #判断是否存在该产品
        stock = Stock.objects.get(stockid=request.POST.get('stockid'), stockname=request.POST.get('stockname'))
        # stock, created = Stock.objects.get_or_create(stockid=request.POST.get('stockid'), stockname=request.POST.get('stockname'))
        if stock:
            newTrade = Trade.objects.create(customer=customer, stock=stock, create=timezone.now())
            #record to trade_memory
            newTrademem = Trade_memory.objects.create(trade=newTrade)
            customer.tradecount += 1
        else:
            raise Exception("stockerror")
        newTrade.status = 0
        newTrade.stockid = request.POST.get('stockid')
        newTrade.stockname = request.POST.get('stockname')

        newTrade.buyprice = buyprice
        newTrade.buycount = buycount

        newTrademem.stockid = newTrade.stockid
        newTrademem.save()

        newTrade.buycash = buycash
        customer.modify = timezone.now()
        # 判断是否VIP和10W+
        if buycash >= 100000:
            customer.tcrude = True

        customer.status = 40
        #如果是首笔交易标记客户状态为有效客户
        if firstTrade:
            customer.first_trade_cash = buycash
            customer.first_trade = timezone.now()
#--------------------------------------------------------------------------------------------------------------------------------
            if customer.sales:
               #绑定开发的真实用户有效客户数加1
               customer.sales.binduser.userprofile.grade += 1
               customer.sales.binduser.userprofile.save()
               #历史有效客户数加1
               userGradeHis, created = customer.sales.binduser.usergradehis_set.get_or_create(user=customer.sales.binduser,
                                                                                  day=datetime.date.today())
               userGradeHis.delta += 1
               userGradeHis.total = customer.sales.binduser.userprofile.grade
               userGradeHis.save()
               #同时建立历史提交数记录
               userCommitHis, created = customer.sales.binduser.usercommithis_set.get_or_create(user=customer.sales.binduser, day=datetime.date.today())
               userCommitHis.total = customer.sales.binduser.userprofile.commit
               userCommitHis.save()
#---------------------------------------------------------------------------------------------------------------------------------
            if buycash >= 100000:
                customer.crude = True

        elif secondTrade:
            customer.vip = True
            if not customer.first_trade:
                customer.first_trade = timezone.now()


        # newTrade.income = request.POST.get('income', 0)
        newTrade.share = request.POST.get('share')
        customer.latest = timezone.now()
        # newTrade.sellprice = request.POST.get('sellprice', '0')
        # newTrade.commission = request.get('commission', 0)
        tradeid = newTrade.id
        newTrade.realteacheruser = request.user
        newTrade.analyst = Analyst.objects.get(analystId=analystId)



        #上传交割单据
        tradefile = request.FILES['file']
        filename = str(tradeid)+'.jpg'
        # jpgfile = "trade/static/trade/images/"+filename
        jpgfile = os.path.join(UPLOAD_ROOT, "trade/images/")+filename
        #如果存在先删除
        if os.path.isfile(jpgfile):
               os.remove(jpgfile)

        file = open(jpgfile, "wb+")

        for chunk in tradefile.chunks():
            file.write(chunk)
        file.close()

        newTrade.save()
        customer.save()

        data['msg'] = "操作成功"
        data['msgLevel'] = "info"
        # logger.error("%s add a trade for customer %s success,customer.status change to %s" % (request.user.username,customer.id,customer.status))
    except Exception as e:
        newTrade.delete()
        traceback.print_exc()
        print(e.__str__())
        if e.__str__() == 'stockerror':
            data['msg'] = "操作失败, 输入错误，或产品库中无此产品，请联系管理员"
        elif str(e.__str__()).__contains__('stock_stock_stockid'):
            data['msg'] = "操作失败, 输入错误，或产品库中无此产品，请联系管理员"
        elif str(e.__str__()).__contains__('Stock matching'):
            data['msg'] = "操作失败, 输入错误，或产品库中无此产品，请联系管理员"
        elif str(e.__str__()).__contains__('stock_stock_stockname'):
            data['msg'] = "操作失败, 输入错误，或产品库中无此产品，请联系管理员"
        elif e.__str__() == 'buycountzero':
            data['msg'] = "操作失败, 购买数量不能为零"
        elif e.__str__() == 'buycashlow':
            data['msg'] = "客户买入资金不足，无法提交"
        else:
            data['msg'] = "操作失败, %s" % e.__str__()
        data['msgLevel'] = "error"
        # logger.error("%s add a trade for customer failed" % (request.user.username))
    return HttpResponse(json.dumps(data))

@login_required()
def handleTrade(request):
    data = {}
    firstTrade = False
    try:
        customer = Customer.objects.get(id=request.POST.get('htcustomerid'))
        # 判断是否首笔交易
        firstTradeObj = Trade.objects.filter(customer=customer).earliest('create')
        if int(request.POST.get('htid')) == firstTradeObj.id:
            firstTrade = True

        newTrade = Trade.objects.get(id=request.POST.get("htid"))
        # 判断是否存在该产品
        stock = Stock.objects.get(stockid=request.POST.get('htstockid'), stockname=request.POST.get('htstockname'))
        # stock, created = Stock.objects.get_or_create(stockid=request.POST.get('htstockid'),
        #                                              stockname=request.POST.get('htstockname'))
        if stock:
            newTrade.stock = stock
        else:
            raise Exception("stockerror")
        newTrade.stockid = request.POST.get('htstockid')
        newTrade.stockname = request.POST.get('htstockname')

        if request.POST.get('statustool')=='20':
            tradeStatus = request.POST.get('statustool')
            tradeBursar = Bursar.objects.get(bursarId=request.POST.get('payDiv'))
            #更改客户绑定财务
            customer.bursar_id = tradeBursar.id
        else:
            tradeStatus = request.POST.get('otherDiv')

        newTrade.status = tradeStatus

        if tradeStatus == '20':
            newTrade.dealtime = timezone.now()
        buyprice = float(request.POST.get('htbuyprice'))
        buycount = int(request.POST.get('htbuycount'))
        newTrade.buyprice = buyprice
        newTrade.buycount = buycount
        buycash = buyprice * buycount
        if firstTrade:
            if buycash < 20000:
                raise Exception("buycashlow")
            customer.first_trade_cash = buycash
            if buycash >= 100000:
                customer.crude = True
            else:
                customer.crude = False
            # customer.first_trade = timezone.now()

        newTrade.buycash = buycash
        customer.modify = timezone.now()

trade/templates/trade/payManage.html
{% extends 'base_nobar.html' %}
{% block title %}收款管理{% endblock %}
{% block content %}
<div class="modal fade" id="payTradeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">收款管理</h4>
            </div>

            <div class="modal-body">
                <!-- The form is placed inside the body of modal -->
                <form id="payTradeForm" method="post" class="form-horizontal">
                    <input type="hidden" value="" class="" id="ptid" name="ptid"/>
                    <div class="form-group">
                        <label class="col-md-offset-2 col-md-2 control-label" for="ptpaytype" >收款方式</label>
                        <div class="col-md-5">
                            <select type="select" class="form-control" id="ptpaytype" name="ptpaytype">
                                <option value="支付宝">支付宝</option>
                                <option value="微信">微信</option>
                                <option value="中国银行">中国银行</option>
                                <option value="农业银行">农业银行</option>
                                <option value="交通银行">交通银行</option>
                                <option value="建设银行">建设银行</option>
                                <option value="工商银行">工商银行</option>
                                <option value="招商银行">招商银行</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-offset-2 col-lg-2 col-md-2 control-label" for="ptpaycash">收款金额</label>
                            <div class="col-lg-5 col-md-5">
                                <input type="text" class="form-control" id="ptpaycash" name="ptpaycash"/>
                            </div>
                    </div>
                    <div class="modal-footer">
                        <div class="form-group">
                            <div class="col-md-5 col-md-offset-3">
                                <button id="payTradeBtn" type="submit" class="btn btn-sm btn-primary">提交</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        formValidator();
        loadTradeDiv();
        loadCustomerDiv();
        $('#payTradeModal').on('hidden.bs.modal', function() {
            resetFormValidator();
        });
    });
    function loadTradeDiv(data){
        var customerId = "{{ customer.id }}";
        data = "customerid=" + customerId + '&'+data;
        $('#tradeDiv').load("{% url 'trade:queryTrade' %}", data);
    }
    function loadCustomerDiv(data){
        var customerId = "{{ customer.id }}";
        data = "customerid=" + customerId + '&'+data;
        $('#customerDiv').load("{% url 'customer:getCustomerById' %}", data);
    }
    function updateParentWindow(){
        window.opener.loadCustomerPayDiv();
    }
    function payTrade(obj){
        $('#ptid').val($(obj).data("ptid"));
        $('#ptpaycash').val($(obj).data("ptpaycash"));
        $('#payTradeModal').modal("show");
    }
    function formValidator(){
        $('#payTradeForm').bootstrapValidator({
            excluded: [':disabled'],
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                ptpaytype: {
                    validators: {
                        notEmpty: {
                            message: '必填项',
                        },
                    }
                },
                ptpaycash: {
                    validators: {
                        notEmpty: {
                            message: '必填项',
                        }
                    }
                },
            },
            submitHandler: function (validator, form, submitButton) {
                $('#payTradeModal').modal('hide');
                $.post(
                    "{% url 'trade:payTrade' %}",
                    form.serialize(),
                    function(result) {
                        showMsgModal(result.msg, result.msgLevel);
                        loadTradeDiv();
                        loadCustomerDiv();
                        updateParentWindow();
                    },
                    'json'
                );
            }
        });
    }
    function resetFormValidator(){
        formValidator();
    }
</script>
<div id="customerDiv"></div>
{#<div class="col-md-2">#}
{#        <button class="btn btn-sm btn-success" data-toggle="modal" data-target="#addTradeModal">新增交易</button>#}
{#</div>#}
    <br/>
    <br/>
<div id="tradeDiv" data-customerid="{{ customer.id }}"></div>
{% endblock %}

trade/templates/trade/queryTrade.html
<div class="modal fade" id="showMsgModal"  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
{#        <div class="modal-content">#}
{#            <div class="modal-header">#}
{#                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>#}
{#                <h4 class="modal-title">交割单据</h4>#}
{#            </div>#}
            <div class="modal-body">
{#                <div id="msgtext" class="alert alert-info" ></div>#}
                <div style="text-align: center; width: 540px; height: 360px"> <img id="imgid" src=" " style="width: auto; height: auto; max-width: 100%; max-height: 100%"/></div>
            </div>
{#        </div>#}
    </div>
</div>
<table class="table table-bordered col-md-12 table-hover">
    <thead class="bg-info">
        <tr>
{#            <td>ID</td>#}
            <td>交易状态</td>
            <td>产品代码</td>
            <td>产品名称</td>
            <td>买入价格</td>
            <td>买入数量</td>
            <td>买入资金</td>
            <td>佣金</td>
            <td>卖出价格</td>
            <td>盈亏</td>
            <td>应收</td>
            <td>实收</td>
            <td>交易时间</td>
            <td>技术分析师</td>
            <td>收款时间</td>
            <td>收款类型</td>
            <td>操作</td>
        </tr>
    </thead>
    <tbody>
    {% if tradePage %}
    {% for tradeObj in tradePage %}
        <tr>
{#            <td>{{ tradeObj.id }}</td>#}
            <td>
                {% if tradeObj.status == 0 %}
                    未出货
                {% elif tradeObj.status == 1 %}
                    退回，{{ tradeObj.message }}
                {% elif tradeObj.status == 10 %}
                    非正常盈收｜下次补亏
                {% elif tradeObj.status == 11 %}
                    非正常盈收｜客户自抛
                {% elif tradeObj.status == 12 %}
                    非正常盈收｜客户拉黑
                {% elif tradeObj.status == 13 %}
                    非正常盈收｜止损做现货
                {% elif tradeObj.status == 14 %}
                    非正常盈收｜超出合作周期
                {% elif tradeObj.status == 15 %}
                    非正常盈收｜业务员虚假承诺
                {% elif tradeObj.status == 16 %}
                    非正常盈收｜少量盈利转做现货
                {% elif tradeObj.status == 17 %}
                    非正常盈收｜少量盈利下次结算
                {% elif tradeObj.status == 18 %}
                    非正常盈收｜客户亏损不再合作
                {% elif tradeObj.status == 19 %}
                    非正常盈收｜客户急需资金提前出货
                {% elif tradeObj.status == 20 %}
                    等待财务收款
                {% elif tradeObj.status == 30 %}
                    已收款
                {% endif %}
            </td>
            <td>{{ tradeObj.stock.stockid}}</td>
            <td> <label id="showfile" type="button" data-fsid="{{ tradeObj.id }}" onclick="showFile(this)">{{ tradeObj.stock.stockname }}</label></td>
            <td>{{ tradeObj.buyprice }}</td>
            <td>{{ tradeObj.buycount}}</td>
            <td>{{ tradeObj.buycash}}</td>
            <td>{{ tradeObj.share}}</td>
            <td>{{ tradeObj.sellprice}}</td>
            <td>{{ tradeObj.income}}</td>
            <td>{{ tradeObj.commission}}</td>
            <td>{{ tradeObj.paycash}}</td>
            <td>{{ tradeObj.create}}</td>
            <td>{{ tradeObj.analyst.binduser.userprofile.nick }}</td>
            <td>{% if tradeObj.paytime %}{{ tradeObj.paytime}}{% endif %}</td>
            <td>{{ tradeObj.paytype}}</td>
            <td>
                {% if request.user.userprofile.title.role_name in "admin teacher ops teachermanager teacherboss" %}
                <button type="button" class="btn btn-sm btn-primary" onclick="handleTrade(this)" {% if tradeObj.status == 30 %} disabled="disabled" {% endif %}
                    data-htid="{{ tradeObj.id }}"
                    data-htstockid="{{ tradeObj.stock.stockid }}"
                    data-htcreate="{{ tradeObj.create.date }}"
                    data-htstockname="{{ tradeObj.stock.stockname }}"
                    data-htbuyprice="{{ tradeObj.buyprice }}"
                    data-htbuycount="{{ tradeObj.buycount }}"
                    data-htshare="{{ tradeObj.share }}"
                    data-htsellprice="{{ tradeObj.sellprice }}"
                    data-htincome="{{ tradeObj.income }}"
                    data-htcommission="{{ tradeObj.commission }}"
                    data-htusertitle = "{{ user_title }}"
                >处理</button>
                {% endif %}
                {% if request.user.userprofile.title.role_name in "admin ops" %}
                <button type="button" class="btn btn-sm btn-danger" onclick="deleteTrade(this)"
                    data-dtid="{{ tradeObj.id }}"
                >删除</button>
                {% endif %}
                {% if request.user.userprofile.title.role_name in "bursar" and tradeObj.status == 20 %}
                <button type="button" class="btn btn-sm btn-primary" onclick="payTrade(this)"
                    data-ptid="{{ tradeObj.id }}"
                    data-ptpaycash="{{ tradeObj.commission }}"
                >收款</button>
                {% endif %}
                {% if request.user.userprofile.title.role_name in "admin ops teachermanage teacherboss" %}
                 <button id="update" type="button" class="btn btn-sm btn-primary" data-toggle="modal" onclick="updateFile(this)"
                    data-udid="{{ tradeObj.id }}"
                >更新</button>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    {% else %}
         <tr><td colspan="15">无交易信息</td></tr>
    {% endif %}
    </tbody>
</table>
<nav class="navbar-right">
  <ul class="pagination">
    <li>
        {% if tradePage.has_previous %}
            <span aria-hidden="true" onclick="loadTradeDiv('page={{ tradePage.previous_page_number }}&{{ requestArgs }}')">&laquo;</span>
        {% endif %}
    </li>
    <li><span class="current">
           第{{ tradePage.number }}/{{ tradePage.paginator.num_pages }}页
        </span></li>
    <li>
        {% if tradePage.has_next %}
            <span aria-hidden="true" onclick="loadTradeDiv('page={{ tradePage.next_page_number }}&{{ requestArgs }}')">&raquo;</span>
        {% endif %}
    </li>
  </ul>
</nav>

<script type="text/javascript">
    function showFile(obj){
        var tradeId = $(obj).data("fsid");
        $.post(
            "{% url 'trade:showFile' %}",
            {"tradeid":tradeId},
            function(result) {
                showFileMsgModal(result.msg, result.msgLevel,result.filename);
            },
            'json'
        );
    };
     function showFileMsgModal(msg,msgLevel,filename){
        $('#msgtext').text(msg);
        if(msgLevel == 'info'){
            $('#msgtext').attr("class",'alert alert-info' );
            $('#imgid').attr("src",filename);
        }else{
            $('#msgtext').attr("class",'alert alert-danger');
        }
        $('#showMsgModal').modal('show');
    }
    $('#showMsgModal').on('hidden.bs.modal', function() {
            $('body').css("padding",0);
    });
</script>