customer/urls.py
from django.conf.urls import include, url
from customer import views
urlpatterns = [
    #for sale
    url(r'^customerManage$', views.customerManage, name='customerManage'),
    url(r'^queryCustomer$', views.queryCustomer, name='queryCustomer'),
    url(r'^addCustomer$', views.addCustomer, name='addCustomer'),
    url(r'^delCustomer$', views.delCustomer, name='delCustomer'),
    url(r'^delCustomerBySale$', views.delCustomerBySale, name='delCustomerBySale'),
    url(r'^checkCustomerPhone$', views.checkCustomerPhone, name='checkCustomerPhone'),
    url(r'^checkCustomerPhoneForEdit$', views.checkCustomerPhoneForEdit, name='checkCustomerPhoneForEdit'),

    #for teacher
    url(r'^customerHandle$', views.customerHandle, name='customerHandle'),
    url(r'^queryCustomerHandle$', views.queryCustomerHandle, name='queryCustomerHandle'),
    url(r'^handleCustomer$', views.handleCustomer, name='handleCustomer'),
    url(r'^handleValidCustomer$', views.handleValidCustomer, name='handleValidCustomer'),
    url(r'^handleValidCustomer$', views.handleValidCustomer, name='handleValidCustomer'),
    url(r'^editSpot$', views.editSpot, name='editSpot'),
    url(r'^handleSpotCustomer$', views.handleSpotCustomer, name='handleSpotCustomer'),
    url(r'^addTeacherCustomer$', views.addTeacherCustomer, name='addTeacherCustomer'),

    #for bursar
    url(r'^customerPay$', views.customerPay, name='customerPay'),
    url(r'^queryCustomerPay$', views.queryCustomerPay, name='queryCustomerPay'),
    url(r'^tradePayManage$', views.tradePayManage, name='tradePayManage'),
    url(r'^queryTradePayManage$', views.queryTradePayManage, name='queryTradePayManage'),

    #for trade
    url(r'^getCustomerById$', views.getCustomerById, name='getCustomerById'),
    url(r'^getSpotCustomerById$', views.getSpotCustomerById, name='getSpotCustomerById'),

    #for report
    url(r'^noTradeCustomerReport$', views.noTradeCustomerReport, name='noTradeCustomerReport'),
    url(r'^tradeTypeReport$', views.tradeTypeReport, name='tradeTypeReport'),
    url(r'^getTeacherDetail$', views.getTeacherDetail, name='getTeacherDetail'),
    url(r'^getStockDetail$', views.getStockDetail, name='getStockDetail'),
    url(r'^dCustomerReport$', views.dCustomerReport, name='dCustomerReport'),
    url(r'^analyzeReport$', views.analyzeReport, name='analyzeReport'),
    url(r'^queryAnalyzeReport$', views.queryAnalyzeReport, name='queryAnalyzeReport'),
    url(r'^sortAnalyzeReport$', views.sortAnalyzeReport, name='sortAnalyzeReport'),
    url(r'^getStockDetailForAnalyze$', views.getStockDetailForAnalyze, name='getStockDetailForAnalyze'),
    url(r'^calcProfitByStockId$', views.calcProfitByStockId, name='calcProfitByStockId'),
    url(r'^resumeDishonestCustomer$', views.resumeDishonestCustomer, name='resumeDishonestCustomer'),



]

ops/urls.py
from django.conf.urls import include, url
from ops import views
urlpatterns = [
    url(r'^userManage$', views.userManage, name='userManage'),
    url(r'^addUser$', views.addUser, name='addUser'),
    url(r'^queryUser$', views.queryUser, name='queryUser'),
    url(r'^delUser$', views.delUser, name='delUser'),
    url(r'^resetPw$', views.resetPw, name='resetPw'),
    url(r'^chargebackSerial$', views.chargebackSerial, name='chargebackSerial'),
    url(r'^checkUserId$', views.checkUserId, name='checkUserId'),
    url(r'^checkEditUserId$', views.checkEditUserId, name='checkEditUserId'),
    url(r'^checkCId$', views.checkCId, name='checkCId'),
    url(r'^checkEditCId$', views.checkEditCId, name='checkEditCId'),
    url(r'^systermLog$', views.systemLog, name='systemLog'),
    url(r'^addFixContent$',views.addFixContent,name='addFixContent'),
    url(r'^queryLog$',views.queryLog,name='queryLog'),
]

shande/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from super import urls as superurls
from ops import urls as opsurls
from sale import urls as saleurls
from customer import urls as customerurls
from teacher import urls as teacherurls
from bursar import urls as bursarurls
from wxqq import urls as wxqqurls
from trade import urls as tradeurls
from spot import urls as spoturls
from stock import urls as stockurls
from analyst import urls as analysturls
from shande.settings import STATIC_ROOT
urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # app super [default]
    url(r'', include(superurls, namespace="super")),

    # app ops
    url(r'^ops/', include(opsurls, namespace="ops")),

    # app sale
    url(r'^sale/', include(saleurls, namespace="sale")),

    # app customer
    url(r'^customer/', include(customerurls, namespace="customer")),

    # app teacher
    url(r'^teacher/', include(teacherurls, namespace="teacher")),

    # app bursar
    url(r'^bursar/', include(bursarurls, namespace="bursar")),

    # app wxqq
    url(r'^wxqq/', include(wxqqurls, namespace="wxqq")),

    # app trade
    url(r'^trade/', include(tradeurls, namespace="trade")),

    # app spot
    url(r'^spot/', include(spoturls, namespace="spot")),

    # app stock
    url(r'^stock/', include(stockurls, namespace="stock")),

    # app analyst
    url(r'^analyst/', include(analysturls, namespace="analyst")),
]
#
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG is False:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.UPLOAD_ROOT)
#     urlpatterns.append(url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),)

spot/urls.py
from django.conf.urls import include, url
from spot import views
urlpatterns = [
    url(r'^teacherManage$', views.teacherManage, name='teacherManage'),
    url(r'^queryTeacher$', views.queryTeacher, name='queryTeacher'),
    url(r'^addTeacher$', views.addTeacher, name='addTeacher'),
    url(r'^addTeacherGroup$', views.addTeacherGroup, name='addTeacherGroup'),
    url(r'^delTeacher$', views.delTeacher, name='delTeacher'),

    url(r'^spotCustomer$', views.spotCustomer, name='spotCustomer'),
    url(r'^querySpotCustomer$', views.querySpotCustomer, name='querySpotCustomer'),

    url(r'^spotManage$', views.spotManage, name='spotManage'),
    url(r'^querySpot$', views.querySpot, name='querySpot'),
    url(r'^addSpot$', views.addSpot, name='addSpot'),
    url(r'^handleSpot$', views.handleSpot, name='handleSpot'),

    url(r'^spotReport$', views.spotReport, name='spotReport'),
    url(r'^getSpotTeacherDetail$', views.getSpotTeacherDetail, name='getSpotTeacherDetail'),


]

spot/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from customer.models import *

# Create your models here.

class Spot(models.Model):
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    create = models.DateTimeField('交易时间')
    # 0 首次入金; 10 加仓; 20 减仓;  30 盈; 40 亏; 99 其他
    type = models.IntegerField('交易动作', default=0)
    cash = models.DecimalField('净入金', max_digits=15, decimal_places=2, default=0)
    profit = models.DecimalField('盈亏', max_digits=15, decimal_places=2, default=0)
    tax = models.DecimalField('手续费', max_digits=15, decimal_places=2, default=0)

spot/views.py
# coding=utf-8
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.db.models import Q

import os
import random
import string
import datetime
import traceback
import json

from shande.settings import BASE_DIR
from shande.util import *
from ops.models import *
from super.models import *
from teacher.models import *
from sale.models import *
from customer.models import *
from spot.models import *

@login_required()
def teacherManage(request):
    if (not request.user.userprofile.title.role_name in ['admin', 'ops']):
        return HttpResponseRedirect("/")
    bindUsers = User.objects.filter(userprofile__title__role_name__in=["spotteacher", "spotmanager"]).order_by("userprofile__nick")
    data = {
        "bindusers": bindUsers,
    }
    return render(request, 'spot/teacherManage.html', data)

@login_required()
def queryTeacher(request):
    teachers = SpotTeacher.objects.all().order_by('teacherId')
    teachers = teachers.filter(teacherId__icontains=request.GET.get('teacherid', ''))
    teachers = teachers.filter(company__icontains=request.GET.get('company', ''))
    teachers = teachers.filter(department__icontains=request.GET.get('department', ''))

    if 'binduser' in request.GET and request.GET['binduser'] != '':
        teachers = teachers.filter(binduser__userprofile__nick__icontains=request.GET.get('binduser'))
    p = Paginator(teachers, 20)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        teacherPage = p.page(page)
    except (EmptyPage, InvalidPage):
        teacherPage = p.page(p.num_pages)

    data = {
        "teacherPage": teacherPage,
        "requestArgs": getArgsExcludePage(request),
    }
    return render(request, 'spot/queryTeacher.html', data)

@login_required()
def addTeacher(request):
    data = {}
    try:

        if request.POST['id'] == "":
            newTeacher = SpotTeacher.objects.create(teacherId=request.POST['teacherid'])
        else:
            newTeacher = SpotTeacher.objects.get(id=request.POST['id'])
            newTeacher.teacherId = request.POST['teacherid']
        binduserid = request.POST.get('binduser', '无')
        if binduserid.isdigit():
            try:
                oldTeacher = SpotTeacher.objects.get(binduser_id=binduserid)
                oldTeacher.binduser = None
                oldTeacher.save()
            except Exception as e:
                # print(e.message)
                # print(e.__str__())
                pass
            newTeacher.binduser = User.objects.get(id=binduserid)
        else:
            newTeacher.binduser = None
        newTeacher.save()
        data['msg'] = "操作成功"
        data['msgLevel'] = "info"
    except Exception as e:
        print(e.__str__())
        print(e.message)
        if str(e.__str__()).__contains__('teacherId'):
            data['msg'] = "操作失败,老师ID已存在"
        elif str(e.__str__()).__contains__('binduser'):
            data['msg'] = "操作失败,用户已绑定老师，请刷新页面重试"
        else:
            data['msg'] = "操作失败,请联系管理员。错误信息:%s" % e.__str__()
        data['msgLevel'] = "error"
    return HttpResponse(json.dumps(data))

@login_required()
def addTeacherGroup(request):
    data = {}
    try:
        company = request.POST.get('teacherCompany')
        department = request.POST.get('teacherDepartment')
        group = request.POST.get('teacherGroup')
        teacherCount = request.POST.get('teacherCount')
        for i in range(1, int(teacherCount) + 1):
            if i < 10:
                index = '0' + str(i)
            else:
                index = str(i)
            teacherId = company + department + group + index
            spotTeacher, created = SpotTeacher.objects.get_or_create(teacherId=teacherId)
            spotTeacher.company = company
            spotTeacher.department = department
            spotTeacher.group = group
            spotTeacher.save()
        data['msg'] = "操作成功"
        data['msgLevel'] = "info"
    except Exception as e:
        print(e.__str__())
        print(e.message)
        if str(e.__str__()).__contains__('teacherId'):
            data['msg'] = "操作失败,老师ID已存在"
        elif str(e.__str__()).__contains__('binduser'):
            data['msg'] = "操作失败,用户已绑定老师，请刷新页面重试"
        else:
            data['msg'] = "操作失败,请联系管理员。错误信息:%s" % e.__str__()
        data['msgLevel'] = "error"
    return HttpResponse(json.dumps(data))

@login_required()
def delTeacher(request):
    data = {}
    try:
        tmpTeacher = SpotTeacher.objects.get(id=request.POST['id'])
        tmpTeacher.delete()
        data['msg'] = "操作成功"
        data['msgLevel'] = "info"
    except Exception as e:
        print(e.__str__())
        data['msg'] = "操作失败"
        data['msgLevel'] = "error"
    return HttpResponse(json.dumps(data))

@login_required()
def spotCustomer(request):
    if (not request.user.userprofile.title.role_name in ['admin', 'ops', 'spotteacher', 'spotmanager','teacher', 'teachermanager', 'teacherboss']):
        return HttpResponseRedirect("/")
    endDate = request.POST.get('endDate', "")
    if endDate == '':
        endDate = datetime.date.today() + datetime.timedelta(days=1)
    else:
        endDate = datetime.datetime.strptime(endDate, "%Y-%m-%d").date()
    startDate = request.POST.get('startDate', "")
    if startDate == "":
        startDate = datetime.date.today() - datetime.timedelta(days=30)
    else:
        startDate = datetime.datetime.strptime(startDate, "%Y-%m-%d").date()
    data = {
        "startDate": str(startDate),
        "endDate": str(endDate),
    }
    return render(request, 'spot/spotCustomer.html', data)

@login_required()
def querySpotCustomer(request):
    customers = Customer.objects.filter(spotStatus='D').order_by('-spotTime')
    # 不同角色看到不同的列表
    if request.user.userprofile.title.role_name in ['spotteacher', 'spotmanager']:
        spotTeacher = SpotTeacher.objects.get(binduser=request.user)
        customers = customers.filter(spotTeacher=spotTeacher)
        customers = customers.exclude(status=99)
    elif request.user.userprofile.title.role_name in ['teacher']:
        teacher = Teacher.objects.get(binduser=request.user)
        customers = customers.filter(teacher=teacher)
        customers = customers.exclude(status=99)
    elif request.user.userprofile.title.role_name in ['teacherboss']:
        company = request.user.userprofile.company
        customers = customers.filter(teacher__company=company)
        customers = customers.exclude(status=99)
    elif request.user.userprofile.title.role_name in ['teachermanager']:
        company = request.user.userprofile.company
        department = request.user.userprofile.department
        customers = customers.filter(teacher__company=company, teacher__department=department)
        customers = customers.exclude(status=99)
    else:
        customers = customers

    # 去掉退回状态的客户
    customers = customers.exclude(status=10)
    customers = customers.exclude(status=30)

    # 按条件查询
    customers = customers.filter(teacher__teacherId__icontains=request.GET.get('teacherid', ''))
    customers = customers.filter(name__icontains=request.GET.get('name', ''))
    customers = customers.filter(phone__icontains=request.GET.get('phone', ''))
    if request.GET.get('wxqq', '') != '':
        customers = customers.filter(Q(wxid="", qqid__icontains=request.GET.get('wxqq')) | Q(qqid="",
                                                                                             wxid__icontains=request.GET.get(
                                                                                                 'wxqq')))
    if request.GET.get('wxqqname', '') != '':
        customers = customers.filter(Q(wxid="", qqname__icontains=request.GET.get('wxqqname')) | Q(qqid="",
                                                                                             wxname__icontains=request.GET.get(
                                                                                                 'wxqqname')))
    if request.GET.get('wxid', '') != '':
        customers = customers.filter(wxid__icontains=request.GET.get('wxid', ''))
    if request.GET.get('wxname', '') != '':
        customers = customers.filter(wxname__icontains=request.GET.get('wxname', ''))
    if request.GET.get('qqid', '') != '':
        customers = customers.filter(qqid__icontains=request.GET.get('qqid', ''))
    if request.GET.get('qqname', '') != '':
        customers = customers.filter(qqname__icontains=request.GET.get('qqname', ''))
    if request.GET.get('startDate', '') != '':
        customers = customers.filter(create__gte=request.GET.get('startDate'))
    if request.GET.get('endDate', '') != '':
        customers = customers.filter(create__lte=request.GET.get('endDate'))
    p = Paginator(customers, 20)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        customerPage = p.page(page)
    except (EmptyPage, InvalidPage):
        customerPage = p.page(p.num_pages)
    data = {
        "customerPage": customerPage,
        "requestArgs": getArgsExcludePage(request),
    }
    return render(request, 'spot/querySpotCustomer.html', data)

@login_required()
def spotManage(request):
    if (not request.user.userprofile.title.role_name in ['admin', 'ops', 'spotteacher', 'spotmanager', 'teacher', 'teachermanager', 'teacherboss']):
        return HttpResponseRedirect("/")
    customerId = request.GET.get("customerId")
    customer = Customer.objects.get(id=customerId)
    data = {
        "customer": customer,
    }
    return render(request, 'spot/spotManage.html', data)

@login_required()
def querySpot(request):
    customerId = request.GET.get("customerid")
    spots = Spot.objects.filter(customer_id=customerId)
    cashTotal = 0

spot/templates/spot/teacherManage.html
{% extends 'base_noheader.html' %}

{% block title %}现货老师管理{% endblock %}
{% block content %}

    <div class="modal fade" id="addTeacherModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">老师管理</h4>
                </div>

                <div class="modal-body">
                    <!-- The form is placed inside the body of modal -->
                    <form id="addTeacherForm" method="post" class="form-horizontal">
                        <div class="form-group">
                            <input type="hidden" value="" class="" id="id" name="id"/>
                            <input type="hidden" value="" class="" id="page" name="page"/>
                            <label class="col-md-offset-2 col-lg-2 col-md-2 control-label" for="teacherid">老师ID</label>
                            <div class="col-lg-5 col-md-5">
                                <input type="text" class="form-control" id="teacherid" name="teacherid"
                                data-bv-notempty="true"
                                data-bv-notempty-message="不允许为空"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-offset-2 col-md-2 control-label" for="binduser" >绑定用户</label>
                            <div class="col-md-5">
                                <select type="select" class="form-control" id="binduser" name="binduser">
                                    <option>无</option>
                                    {% if bindusers %}
                                        {% for binduser in bindusers %}
                                            <option value="{{ binduser.id }}"> {{ binduser.username }}-{{ binduser.userprofile.nick }}</option>
                                        {% endfor %}
                                    {% endif %}
                                </select>

                            </div>
                        </div>
                        <div class="modal-footer">
                            <div class="form-group">
                                <div class="col-md-5 col-md-offset-3">
                                    <button id="addTeacherBtn" type="submit" class="btn btn-sm btn-primary">提交</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="addTeacherGroupModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">现货老师组管理</h4>
                </div>

                <div class="modal-body">
                    <!-- The form is placed inside the body of modal -->
                    <form id="addTeacherGroupForm" method="post" class="form-horizontal">
                        <div class="form-group">
                            <label class="col-md-offset-2 col-lg-2 col-md-2 control-label" for="teacherCompany">老师公司</label>
                            <div class="col-lg-5 col-md-5">
                                <input type="text" class="form-control" id="teacherCompany" name="teacherCompany"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-offset-2 col-md-2 control-label" for="teacherDepartment" >老师部门</label>
                            <div class="col-md-5">
                                <input type="text" class="form-control" id="teacherDepartment" name="teacherDepartment"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-offset-2 col-md-2 control-label" for="teacherGroup" >老师组</label>
                            <div class="col-md-5">
                                <input type="text" class="form-control" id="teacherGroup" name="teacherGroup"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-offset-2 col-md-2 control-label" for="teacherCount" >老师数量</label>
                            <div class="col-md-5">
                                <input type="text" class="form-control" id="teacherCount" name="teacherCount"/>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <div class="form-group">
                                <div class="col-md-5 col-md-offset-3">
                                    <button id="addTeacherGroupBtn" type="submit" class="btn btn-sm btn-primary">提交</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
    $(function () {
        formValidator();
        loadTeacherDiv();
        $('#addTeacherModal').on('hidden.bs.modal', function() {
            resetFormValidator();
        });
        $('#addTeacherGroupModal').on('hidden.bs.modal', function() {
            resetFormValidator();
        });
    });
    function resetFormValidator(){
        var teacherFormSelector = $('#addTeacherForm');
        teacherFormSelector.find(':input').not('#page').val("");
        teacherFormSelector.data('bootstrapValidator').destroy();
        var teacherGroupFormSelector = $('#addTeacherGroupForm');
        teacherGroupFormSelector.find(':input').not('#page').val("");
        teacherGroupFormSelector.data('bootstrapValidator').destroy();
        $('#searchTeacherForm').data('bootstrapValidator').destroy();
        formValidator();
    }
    function loadTeacherDiv(data){
        $('#teacherDiv').load("{% url 'spot:queryTeacher' %}", data);
    }
    function formValidator(){
        $('#addTeacherForm').bootstrapValidator({
            excluded: [':disabled'],
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                teacherid: {
                    validators: {
                        notEmpty: {
                            message: '必填项'
                        }
                    }
                }
            },
            submitHandler: function (validator, form, submitButton) {
                $('#addTeacherModal').modal('hide');
                $.post(
                    "{% url 'spot:addTeacher' %}",
                    form.serialize(),
                    function(result) {
                        showMsgModal(result.msg, result.msgLevel);
                        data = 'page='+$('#page').val();
                        loadTeacherDiv(data);
                    },
                    'json'
                );
            }
        });
        $('#addTeacherGroupForm').bootstrapValidator({
            excluded: [':disabled'],
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                teacherCompany: {
                    validators: {
                        notEmpty: {
                            message: '必填项'
                        }
                    }
                },
                teacherDepartment: {
                    validators: {
                        notEmpty: {
                            message: '必填项'
                        }
                    }
                },
                teacherGroup: {
                    validators: {
                        notEmpty: {
                            message: '必填项'
                        }
                    }
                },
                teacherCount: {
                    validators: {
                        notEmpty: {
                            message: '必填项',
                        },
                    }
                },
            },
            submitHandler: function (validator, form, submitButton) {
                $('#addTeacherGroupModal').modal('hide');
                $.post(
                    "{% url 'spot:addTeacherGroup' %}",
                    form.serialize(),
                    function(result) {
                        showMsgModal(result.msg, result.msgLevel);
                        loadTeacherDiv();
                    },
                    'json'
                );
            }
        });
        $('#searchTeacherForm').bootstrapValidator({
            excluded: [':disabled'],
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
            },
            submitHandler: function (validator, form, submitButton) {
                loadTeacherDiv(form.serialize());
                resetFormValidator()
            }
        });
    }
    function editTeacher(obj){
        $('#id').val($(obj).data("id"));
        $('#page').val($(obj).data("page"));
        $('#teacherid').val($(obj).data("teacherid"));
        $('#company').val($(obj).data("company"));
        $('#department').val($(obj).data("department"));
        $('#binduser').val($(obj).data("binduser"));
        $('#addTeacherModal').modal("show");
    }
    function delTeacher(obj){
        if(confirm("删除确认")){
            var id = $(obj).data("id");
            $.post(
                "{% url 'spot:delTeacher' %}",
                {id:id},
                function(result) {
                    showMsgModal(result.msg, result.msgLevel);
                    loadTeacherDiv();
                },
                'json'
            );
        }
    }
    </script>
    <br/>
    <br/>
    <form id="searchTeacherForm" method="POST" class="form-horizontal ">
        <div class="form-group">
            <label class="col-md-1 control-label">公司</label>
            <div class="col-md-2 form-inline">
                 <input type="text" class="form-control" value="{{ company }}" name="company"/>
            </div>
            <label class="col-md-1 control-label">部门</label>
            <div class="col-md-2 form-inline">
                 <input type="text" class="form-control" value="{{ department }}" name="department"/>
            </div>
            <label class="col-md-1 control-label"></label>
            <div class="col-md-2">
{#                    <button class="btn btn-sm btn-success" data-toggle="modal" data-target="#addTeacherModal">新增老师</button>#}
                    <button class="btn btn-sm btn-success" data-toggle="modal" data-target="#addTeacherGroupModal">新增老师组</button>
            </div>

        </div>
        <div class="form-group">
            <label class="col-md-1 control-label">老师ID</label>
            <div class="col-md-2 form-inline">
                 <input type="text" class="form-control" value="{{ teacherid }}" name="teacherid"/>
            </div>
            <label class="col-md-1 control-label">绑定用户</label>
            <div class="col-md-2 form-inline">
                 <input type="text" class="form-control" value="{{ binduser }}" name="binduser"/>
            </div>
            <label class="col-md-1 control-label"></label>
            <div class="col-md-2">
                    <button type="submit" class="btn btn-sm btn-primary" >搜索</button>
            </div>
        </div>
    </form>
    <div id="teacherDiv"></div>
{% endblock %}