customer/urls.py
from django.conf.urls import include, url
from customer import views
urlpatterns = [
    #for sale
    url(r'^customerManage$', views.customerManage, name='customerManage'),
    url(r'^queryCustomer$', views.queryCustomer, name='queryCustomer'),
    url(r'^addCustomer$', views.addCustomer, name='addCustomer'),
    url(r'^delCustomer$', views.delCustomer, name='delCustomer'),
    url(r'^delCustomerBySale$', views.delCustomerBySale, name='delCustomerBySale'),
    url(r'^checkCustomerPhone$', views.checkCustomerPhone, name='checkCustomerPhone'),
    url(r'^checkCustomerPhoneForEdit$', views.checkCustomerPhoneForEdit, name='checkCustomerPhoneForEdit'),

    #for teacher
    url(r'^customerHandle$', views.customerHandle, name='customerHandle'),
    url(r'^queryCustomerHandle$', views.queryCustomerHandle, name='queryCustomerHandle'),
    url(r'^handleCustomer$', views.handleCustomer, name='handleCustomer'),
    url(r'^handleValidCustomer$', views.handleValidCustomer, name='handleValidCustomer'),
    url(r'^handleValidCustomer$', views.handleValidCustomer, name='handleValidCustomer'),
    url(r'^editSpot$', views.editSpot, name='editSpot'),
    url(r'^handleSpotCustomer$', views.handleSpotCustomer, name='handleSpotCustomer'),
    url(r'^addTeacherCustomer$', views.addTeacherCustomer, name='addTeacherCustomer'),

    #for bursar
    url(r'^customerPay$', views.customerPay, name='customerPay'),
    url(r'^queryCustomerPay$', views.queryCustomerPay, name='queryCustomerPay'),
    url(r'^tradePayManage$', views.tradePayManage, name='tradePayManage'),
    url(r'^queryTradePayManage$', views.queryTradePayManage, name='queryTradePayManage'),

    #for trade
    url(r'^getCustomerById$', views.getCustomerById, name='getCustomerById'),
    url(r'^getSpotCustomerById$', views.getSpotCustomerById, name='getSpotCustomerById'),

    #for report
    url(r'^noTradeCustomerReport$', views.noTradeCustomerReport, name='noTradeCustomerReport'),
    url(r'^tradeTypeReport$', views.tradeTypeReport, name='tradeTypeReport'),
    url(r'^getTeacherDetail$', views.getTeacherDetail, name='getTeacherDetail'),
    url(r'^getStockDetail$', views.getStockDetail, name='getStockDetail'),
    url(r'^dCustomerReport$', views.dCustomerReport, name='dCustomerReport'),
    url(r'^analyzeReport$', views.analyzeReport, name='analyzeReport'),
    url(r'^queryAnalyzeReport$', views.queryAnalyzeReport, name='queryAnalyzeReport'),
    url(r'^sortAnalyzeReport$', views.sortAnalyzeReport, name='sortAnalyzeReport'),
    url(r'^getStockDetailForAnalyze$', views.getStockDetailForAnalyze, name='getStockDetailForAnalyze'),
    url(r'^calcProfitByStockId$', views.calcProfitByStockId, name='calcProfitByStockId'),
    url(r'^resumeDishonestCustomer$', views.resumeDishonestCustomer, name='resumeDishonestCustomer'),



]

ops/urls.py
from django.conf.urls import include, url
from ops import views
urlpatterns = [
    url(r'^userManage$', views.userManage, name='userManage'),
    url(r'^addUser$', views.addUser, name='addUser'),
    url(r'^queryUser$', views.queryUser, name='queryUser'),
    url(r'^delUser$', views.delUser, name='delUser'),
    url(r'^resetPw$', views.resetPw, name='resetPw'),
    url(r'^chargebackSerial$', views.chargebackSerial, name='chargebackSerial'),
    url(r'^checkUserId$', views.checkUserId, name='checkUserId'),
    url(r'^checkEditUserId$', views.checkEditUserId, name='checkEditUserId'),
    url(r'^checkCId$', views.checkCId, name='checkCId'),
    url(r'^checkEditCId$', views.checkEditCId, name='checkEditCId'),
    url(r'^systermLog$', views.systemLog, name='systemLog'),
    url(r'^addFixContent$',views.addFixContent,name='addFixContent'),
    url(r'^queryLog$',views.queryLog,name='queryLog'),
]

sale/urls.py
from django.conf.urls import include, url
from sale import views
urlpatterns = [
    url(r'^saleManage$', views.saleManage, name='saleManage'),
    url(r'^querySale$', views.querySale, name='querySale'),
    url(r'^addSale$', views.addSale, name='addSale'),
    url(r'^addSaleGroup$', views.addSaleGroup, name='addSaleGroup'),
    url(r'^delSale$', views.delSale, name='delSale'),

    url(r'^saleManagerPasswordManage$', views.saleManagerPasswordManage, name='saleManagerPasswordManage'),
    url(r'^addSaleManagerPassword$', views.addSaleManagerPassword, name='addSaleManagerPassword'),
    url(r'^delSaleManagerPassword$', views.delSaleManagerPassword, name='delSaleManagerPassword'),

    url(r'^saleKpiReport$', views.saleKpiReport, name='saleKpiReport'),
    url(r'^getCompanyDetail$', views.getCompanyDetail, name='getCompanyDetail'),
    url(r'^getDepartmentDetail$', views.getDepartmentDetail, name='getDepartmentDetail'),
    url(r'^getDepartmentGroupDetail$', views.getDepartmentGroupDetail, name='getDepartmentGroupDetail'),
    url(r'^getGroupDetail$', views.getGroupDetail, name='getGroupDetail'),
    url(r'^getSaleDetail$', views.getSaleDetail, name='getSaleDetail'),

    url(r'^dishonestCustomerReport$', views.dishonestCustomerReport, name='dishonestCustomerReport'),
    url(r'^dishonestCustomer$', views.dishonestCustomer, name='dishonestCustomer'),
    url(r'^queryDishonestCustomer$', views.queryDishonestCustomer, name='queryDishonestCustomer'),
    url(r'^saleKpiReportSerial$', views.saleKpiReportSerial, name='saleKpiReportSerial'),
    url(r'^saleKpiReportForManager$', views.saleKpiReportForManager, name='saleKpiReportForManager'),


]

shande/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from super import urls as superurls
from ops import urls as opsurls
from sale import urls as saleurls
from customer import urls as customerurls
from teacher import urls as teacherurls
from bursar import urls as bursarurls
from wxqq import urls as wxqqurls
from trade import urls as tradeurls
from spot import urls as spoturls
from stock import urls as stockurls
from analyst import urls as analysturls
from shande.settings import STATIC_ROOT
urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # app super [default]
    url(r'', include(superurls, namespace="super")),

    # app ops
    url(r'^ops/', include(opsurls, namespace="ops")),

    # app sale
    url(r'^sale/', include(saleurls, namespace="sale")),

    # app customer
    url(r'^customer/', include(customerurls, namespace="customer")),

    # app teacher
    url(r'^teacher/', include(teacherurls, namespace="teacher")),

    # app bursar
    url(r'^bursar/', include(bursarurls, namespace="bursar")),

    # app wxqq
    url(r'^wxqq/', include(wxqqurls, namespace="wxqq")),

    # app trade
    url(r'^trade/', include(tradeurls, namespace="trade")),

    # app spot
    url(r'^spot/', include(spoturls, namespace="spot")),

    # app stock
    url(r'^stock/', include(stockurls, namespace="stock")),

    # app analyst
    url(r'^analyst/', include(analysturls, namespace="analyst")),
]
#
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG is False:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.UPLOAD_ROOT)
#     urlpatterns.append(url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),)

sale/views.py
# coding=utf-8
import json

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.db.models import Q, Count
from django.db import connection
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User
import datetime, logging, time
from sale.models import *
from customer.models import *
from shande.util import *

logger = logging.getLogger("django")
@login_required()
def saleManage(request):
    # t1 = time.clock()
    if (not request.user.userprofile.title.role_name in ['admin', 'ops', 'saleboss']):
        return HttpResponseRedirect("/")
    bindUsers = User.objects.filter(userprofile__title__role_name='sale').order_by("username")
    if request.user.userprofile.title.role_name == 'saleboss':
        bindUsers = bindUsers.filter(userprofile__company=request.user.userprofile.company)
    bindTeachers = Teacher.objects.filter(binduser__isnull=False).order_by("teacherId")
    # for sale in Sale.objects.all():
    #     bindUsers = bindUsers.filter(~Q(id=sale.binduser.id))
    data = {
        "bindusers": bindUsers,
        "bindteachers": bindTeachers,
    }
    # t2 = time.clock()
    # logger.error("saleMange cost time: %f"%(t2-t1))
    return render(request, 'sale/saleManage.html', data)

@login_required()
def querySale(request):
    # t1 = time.clock()
    if(request.GET.get('saleid') or request.GET.get('department')
       or request.GET.get('binduser') or request.GET.get('bindteacher')):
       sales = Sale.objects.all().order_by('saleId')
       #不同的用户看到不同的列表
       if request.user.userprofile.title.role_name == 'saleboss':
           sales = sales.filter(company=request.user.userprofile.company)

       sales = sales.filter(saleId__icontains=request.GET.get('saleid', ''))
       sales = sales.filter(company__icontains=request.GET.get('company', ''))
       sales = sales.filter(department__icontains=request.GET.get('department', ''))
       if 'binduser' in request.GET and request.GET['binduser'] != '':
           sales = sales.filter(binduser__userprofile__nick__icontains=request.GET.get('binduser'))
       if 'bindteacher' in request.GET and request.GET['bindteacher'] != '':
           sales = sales.filter(bindteacher__teacherId__icontains=request.GET.get('bindteacher'))
       if 'bindbursar' in request.GET and request.GET['bindbursar'] != '':
           sales = sales.filter(bindteacher__bindbursar__bursarId__icontains=request.GET.get('bindbursar'))

       p = Paginator(sales, 25)
       try:
           page = int(request.GET.get('page', '1'))
       except ValueError:
           page = 1
       try:
           salePage = p.page(page)
       except (EmptyPage, InvalidPage):
           salePage = p.page(p.num_pages)
       showContent = "True"
       showContent = json.dumps(showContent)
       data = {
           "salePage": salePage,
           "requestArgs": getArgsExcludePage(request),
           "showContent": showContent,
       }
    else:
        showContent = "False"
        showContent = json.dumps(showContent)
        data = {
            "showContent": showContent,
        }
    # t2 = time.clock()
    # logger.error("querySale cost time: %f" % (t2 - t1))
    return render(request, 'sale/querySale.html', data)

@login_required()
def addSale(request):
    # t1 = time.clock()
    data = {}
    try:
        if request.POST['id'] == "":#新建开发ID
            newSale = Sale.objects.create(saleId=request.POST['saleid'])
        else:#修改开发ID信息
            newSale = Sale.objects.get(id=request.POST['id'])
            newSale.saleId = request.POST['saleid']

        if request.POST.get('bindusername'):
            # binduserid = request.POST.get('binduser', '无')
            if User.objects.get(username=request.POST.get('bindusername','')):
                user = User.objects.get(username=request.POST.get('bindusername',''))
                binduserid = str(user.id)
        else:
            binduserid = '无'

        if binduserid.isdigit():
            try:
                oldSale = Sale.objects.get(binduser_id=binduserid)

                oldSale.binduser = None
                oldSale.save()
            except Exception as e:
                # print(e.message)
                # print(e.__str__())
                pass
            newSale.binduser = User.objects.get(id=binduserid)
        else:
            newSale.binduser = None
        #开发ID修改了绑定的真实用户 ，则更新所有相关的未提交客户真实开发用户信息
        customers = newSale.customer_set.filter(Q(status=0)|Q(status=10)|Q(status=30))
        for customer in customers:
            customer.realuser = newSale.binduser
            customer.save()
        #newSale.bindteacher = getTeacherBySaleId(request.POST['saleid'])
        # newSale.company = request.POST['company']
        # newSale.department = request.POST['department']

        teacher = Teacher.objects.get(teacherId=request.POST.get('bindteacherId', ''))
        if teacher:
            # bindteacher = request.POST.get('bindteacher', '无')
             bindteacher = str(teacher.id)
        else:
            bindteacher = '无'
        if bindteacher.isdigit():
            # teacher = Teacher.objects.get(id=request.POST.get('bindteacher'))
            teacher = Teacher.objects.get(id=bindteacher)
            newSale.bindteacher = teacher
        else:
            newSale.bindteacher = None
        #更换开发绑定的老师，将该开发所有的未提交的客户对应的老师都修改为新的老师
        customers = newSale.customer_set.filter(Q(status=0)|Q(status=30)|Q(status=10))
        for customer in customers:
            customer.teacher = newSale.bindteacher
            customer.save()
        newSale.save()
        data['msg'] = "操作成功"
        data['msgLevel'] = "info"
    except Exception as e:
        print(e.__str__())
        print(e.message)
        if str(e.__str__()).__contains__('saleId'):
            data['msg'] = "操作失败,开发ID已存在"
        elif str(e.__str__()).__contains__('binduser'):
            data['msg'] = "操作失败,用户已绑定开发，请刷新页面重试"
        else:
            data['msg'] = "操作失败,请联系管理员。错误信息:%s" % e.__str__()
        data['msgLevel'] = "error"
    # t2 = time.clock()
    # logger.error("addSale cost time: %f" % (t2 - t1))
    return HttpResponse(json.dumps(data))

@login_required()
def addSaleGroup(request):
    # t1 = time.clock()
    data = {}
    try:
        company = request.POST.get('saleCompany')
        department = request.POST.get('saleDepartment')
        group = request.POST.get('saleGroup')
        saleCount = request.POST.get('saleCount')
        for i in range(1, int(saleCount)+1):
            if i<10:
                index = '0' +str(i)
            else:
                index = str(i)
            saleId = company + group + department + index
            sale, created = Sale.objects.get_or_create(saleId=saleId)
            sale.company = company
            sale.department = department
            sale.group = group
            sale.save()

        data['msg'] = "操作成功"
        data['msgLevel'] = "info"
    except Exception as e:
        print(e.__str__())
        if str(e.__str__()).__contains__('saleId'):
            data['msg'] = "操作失败,开发ID已存在"
        elif str(e.__str__()).__contains__('binduser'):
            data['msg'] = "操作失败,用户已绑定开发，请刷新页面重试"
        else:
            data['msg'] = "操作失败,请联系管理员。错误信息:%s" % e.__str__()
        data['msgLevel'] = "error"
    # t2 = time.clock()
    # logger.error("addSaleGroup cost time: %f" % (t2 - t1))
    return HttpResponse(json.dumps(data))

@login_required()
def delSale(request):
    data = {}
    try:
        tmpSale = Sale.objects.get(id=request.POST['id'])
        tmpSale.delete()
        data['msg'] = "操作成功"
        data['msgLevel'] = "info"
    except Exception as e:
        print(e.__str__())
        data['msg'] = "操作失败"
        data['msgLevel'] = "error"
    return HttpResponse(json.dumps(data))

@login_required()
def saleManagerPasswordManage(request):
    if (not request.user.userprofile.title.role_name in ['admin', 'ops', 'salemanager', 'saleboss']):
        return HttpResponseRedirect("/")
    passwordList = SaleManagerPassword.objects.all().order_by("company", "department")
    if request.user.userprofile.title.role_name in ['saleboss']:
        company = request.user.userprofile.company
        passwordList = passwordList.filter(company=company)
    elif request.user.userprofile.title.role_name in ['salemanager']:
        company = request.user.userprofile.company
        department = request.user.userprofile.department
        passwordList = passwordList.filter(company=company, department=department)
    else:
        passwordList = passwordList

    data = {
        "passwordList": passwordList,
    }
    return render(request, 'sale/saleManagerPasswordManage.html', data)

@login_required()
def addSaleManagerPassword(request):
    try:
        SaleManagerPassword.objects.create(company=request.POST.get('company'),
                                           department=request.POST.get('department'),
                                           password=request.POST.get('password'))
    except Exception as e:
        print(e.__str__())
        print(e.message)
    return HttpResponseRedirect('/sale/saleManagerPasswordManage')

@login_required()
def delSaleManagerPassword(request):
    try:
        SaleManagerPassword.objects.get(id=request.GET.get("id")).delete()
    except Exception as e:
        print(e.__str__())
        print(e.message)
    return HttpResponseRedirect('/sale/saleManagerPasswordManage')

@login_required()
def saleKpiReport(request):
    # t1 = time.clock()
    if (not request.user.userprofile.title.role_name in ['admin', 'ops', 'salemanager', 'saleboss','bursarmanager']):
        return HttpResponseRedirect("/")
    endDate = request.POST.get('endDate', "")
    if endDate == '':
        endDate = datetime.date.today() + datetime.timedelta(days=1)
    else:

sale/templates/sale/saleKpiReport.html
{% extends 'base_full_noheader.html' %}
{% load company_tags %}
{% block title %}开发绩效报表{% endblock %}
{% block content %}
    <br/>
    <h1>
        <div class="alert alert-success" style="text-align:center">

            {% if request.user.userprofile.title.role_name == 'saleboss' %}
                {{ request.user.userprofile.company }}公司开发绩效汇总表
            {% else %}
                开发绩效汇总表
            {% endif %}
        </div>
    </h1>
    <hr/>
    <form id="searchKpiForm" method="POST" class="form-horizontal " action="#">
    <div class="form-group">
        <label class="col-md-1 control-label">时间范围</label>
        <div class="col-md-2 ">
             <input type="date"  class="form-control datetime" value="{{ startDate }}" name="startDate" id="startDate"
             title="起始时间"/>
        </div>
        <label class="col-md-1 control-label"></label>
        <div class="col-md-2 ">
             <input type="date"  class="form-control datetime" value="{{ endDate }}" name="endDate" id="endDate"
             title="结束时间"/>
        </div>
        <label class="col-md-1 control-label"></label>
        <div class="col-md-2">
                <button type="submit" class="btn btn-sm btn-primary" >搜索</button>
        </div>
    </div>
</form>
<table class="table table-bordered">
    <thead class="bg-info" id="companyHeader">
        <th width="2%">名次</th>
        <th width="2%">公司</th>
        <th width="5%">有效客户</th>
        <th width="5%">10W+客户</th>
        <th width="5%">合计买入资金</th>
        <th width="5%">微信好友新增</th>
{#        <th width="5%">微信好友总数</th>#}
        <th width="5%">QQ好友新增</th>
{#        <th width="5%">QQ好友总数</th>#}
        <th width="5%">退单率</th>
{#        <th width="5%">不诚信客户</th>#}
    </thead>
    <tbody>
        {% for company in companys %}
            {% if request.user.userprofile.title.role_name in 'saleboss salemanager' and request.user.userprofile.company == company.company or request.user.userprofile.title.role_name in 'admin ops' %}

        <tr data-company="{{ company.company }}" id="company_row_{{ company.company }}" ondblclick="showCompanyDetail(this)" class="company_row">
            <td>{{ forloop.counter }}</td>
            <td>{{ company.company }}</td>
            <td>{{ company.dcount }}</td>
            <td>{% getCrudeCountByCompany company.company startDate endDate %}</td>
            <td>{% getTotalBuyCashByCompany company.company startDate endDate %}</td>
            <td>{% getWxFriendDeltaByCompany company.company startDate endDate %}</td>
{# ----------           <td>{% getWxFriendTotalByCompany company.company %}</td>#}
            <td>{% getQqFriendDeltaByCompany company.company startDate endDate %}</td>
{#  ---------          <td>{% getQqFriendTotalByCompany company.company%}</td>#}
            <td>{% getChargebackByCompany company.company startDate endDate %}</td>
{#  -------          <td>{% getDishonestByCompany company.company startDate endDate %}</td>#}
        </tr>
        <tr style="padding:0;"><td colspan="11" style="padding:0;">
            <div id="company_detail_row_{{ company.company }}" class="company_detail_row" style="margin-left:50px;margin-top:5px;display:none;"></div>
        </td></tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>
<script type="text/javascript">
    {% if request.user.userprofile.title.role_name == 'salemanager' %}
        $(function(){
            var company = "{{ request.user.userprofile.company }}";
            var companyRow = $('#company_row_'+company);
            companyRow.dblclick();
            companyRow.hide();
            $('#companyHeader').hide();
        });
    {% endif %}
    function showCompanyDetail(obj){
        $('.company_detail_row').slideUp();
        $('.company_row').removeClass("bg-danger");
        company = $(obj).data('company');
        companyDetailRowSelector = $('#company_detail_row_'+company);
        if(companyDetailRowSelector.is(':hidden')){
            companyDetailRowSelector.slideDown();
            $('#company_row_'+company).addClass("bg-danger");
            loadCompanyDetail(company);
        }else{
            companyDetailRowSelector.slideUp();
        }
    }
    function loadCompanyDetail(company){
        companyDetailRowSelector = $('#company_detail_row_'+company);
        var startDate = $('#startDate').val();
        var endDate = $('#endDate').val();

        $.ajax({
            url: "{% url 'sale:getCompanyDetail' %}",
            type: 'POST',
            async: true,
            data: { "company": company, "startDate": startDate, "endDate": endDate },
            beforeSend:  function(){
                companyDetailRowSelector.html('<img src="/static/assets/img/loading.gif">')
            },
            success: function (data) {
                companyDetailRowSelector.html(data);
            }
        });
    }
    function showDepartmentDetail(obj){
        $('.department_detail_row').slideUp();
        $('.department_row').removeClass("bg-danger");
        company = $(obj).data('company');
        department = $(obj).data('department');
        departmentDetailRowSelector = $('#department_detail_row_'+company+'_'+department);
        if(departmentDetailRowSelector.is(':hidden')){
            departmentDetailRowSelector.slideDown();
            $('#department_row_'+company+'_'+department).addClass('bg-danger');
            loadDepartmentDetail(company, department);
        }else{
            departmentDetailRowSelector.slideUp();
        }
    }
    function loadDepartmentDetail(company, department) {
        departmnetDetailRowSelector = $('#department_detail_row_'+company+'_'+department);
        var startDate = $('#startDate').val();
        var endDate = $('#endDate').val();
        $.ajax({
            url: "{% url 'sale:getDepartmentGroupDetail' %}",
            type: 'POST',
            async: true,
            data: { "company": company, "department": department, "startDate": startDate, "endDate": endDate  },
            beforeSend:  function(){
                departmentDetailRowSelector.html('<img src="/static/assets/img/loading.gif">')
            },
            success: function (data) {
                departmentDetailRowSelector.html(data);
            }
        });
    }
    function showGroupDetail(obj){
        $('.group_detail_row').slideUp();
        company = $(obj).data('company');
        department = $(obj).data('department');
        group = $(obj).data('group');
        groupDetailRowSelector = $('#group_detail_row_'+company+'_'+department+'_'+group);
        if(groupDetailRowSelector.is(':hidden')){
            groupDetailRowSelector.slideDown();
            loadGroupDetail(company, department, group);
        }else{
            groupDetailRowSelector.slideUp();
        }
    }
    function loadGroupDetail(company, department, group) {
        groupDetailRowSelector = $('#group_detail_row_'+company+'_'+department+'_'+group);
        $.ajax({
            url: "{% url 'sale:getGroupDetail' %}",
            type: 'POST',
            async: true,
            data: { "company": company, "department": department, "group":group },
            beforeSend:  function(){
                groupDetailRowSelector.html('<img src="/static/assets/img/loading.gif">')
            },
            success: function (data) {
                groupDetailRowSelector.html(data);
            }
        });
    }
    function showSaleDetail(obj) {
        $('.sale_detail_row').slideUp();
        company = $(obj).data('company');
        department = $(obj).data('department');
        group = $(obj).data('group');
        sale = $(obj).data('sale');
        saleDetailRowSelector = $('#sale_detail_row_'+company+'_'+department+'_'+group+'_'+sale);
        if(saleDetailRowSelector.is(':hidden')){
            saleDetailRowSelector.slideDown();
            loadSaleDetail(company, department, group, sale);
        }else{
            saleDetailRowSelector.slideUp();
        }
    }
    function loadSaleDetail(company, department, group, sale) {
        saleDetailRowSelector = $('#sale_detail_row_'+company+'_'+department+'_'+group+'_'+sale);
        var startDate = $('#startDate').val();
        var endDate = $('#endDate').val();
        $.ajax({
            url: "{% url 'sale:getSaleDetail' %}",
            type: 'POST',
            async: true,
            data: { "company": company, "department": department, "group": group, "sale": sale, "startDate": startDate, "endDate": endDate },
            beforeSend:  function(){
                saleDetailRowSelector.html('<img src="/static/assets/img/loading.gif">')
            },
            success: function (data) {
                saleDetailRowSelector.html(data);
            }
        });
    }
</script>
{% endblock %}

sale/templates/sale/saleManagerPasswordManage.html
{% extends 'base_full_noheader.html' %}

{% block title %}部门密钥管理{% endblock %}
{% block content %}
<form id="searchCustomerForm" method="POST" class="form-horizontal" action="{% url 'sale:addSaleManagerPassword' %}">
    {% if request.user.userprofile.title.role_name in "admin ops saleboss salemanager" %}
        <div class="form-group">
            <label class="col-md-1 col-md-offset-2 control-label">公司</label>
            <div class="col-md-1">
                 <input type="text" class="form-control" value="{{ request.user.userprofile.company }}" name="company"
                        {% if request.user.userprofile.title.role_name in "saleboss salemanager" %} readonly {% endif %}
                 />
            </div>
            <label class="col-md-1 control-label">部门</label>
            <div class="col-md-1">
                 <input type="text" class="form-control" value="{{ request.user.userprofile.department }}" name="department"
                        {% if request.user.userprofile.title.role_name in "salemanager" %} readonly {% endif %}
                 />
            </div>
            <label class="col-md-1 control-label">密码</label>
            <div class="col-md-1">
                 <input type="text" class="form-control" value="{{ password }}" name="password" required/>
            </div>
            <div class="col-md-1">
                    <button type="submit" class="btn btn-sm btn-primary" >新增</button>
            </div>
        </div>
    {% endif %}
</form>
<div class="col-md-offset-2 col-md-8">
<table class="table table-bordered col-md-12 table-hover">
    <thead class="bg-info">
        <tr>
{#            <td>ID</td>#}
            <td>公司</td>
            <td>部门</td>
            <td>密码</td>
            <td>操作</td>
        </tr>
    </thead>
    <tbody>
    {% for password in passwordList %}
        <tr>
{#            <td>{{ password.id }}</td>#}
            <td>{{ password.company }}</td>
            <td>{{ password.department }}</td>
            <td>{{ password.password }}</td>
            <td>
{#                <button type="button" class="btn btn-sm btn-primary" onclick="editPassword(this)"#}
{#                    data-id="{{ password.id }}"#}
{#                >修改</button>#}

                <button type="button" class="btn btn-sm btn-danger" onclick="delPassword(this)"
                    data-id="{{ password.id }}">删除</button>
            </td>
        </tr>
    {% empty %}
        <tr><td colspan="4">无部门密钥</td></tr>
    {% endfor %}

    </tbody>
</table>
</div>
<script type="text/javascript">
    function delPassword(obj){
         window.open("{% url 'sale:delSaleManagerPassword'%}?id="+$(obj).data("id"), "_self");
    }
</script>
{% endblock %}