ops/urls.py
from django.conf.urls import include, url
from ops import views
urlpatterns = [
    url(r'^userManage$', views.userManage, name='userManage'),
    url(r'^addUser$', views.addUser, name='addUser'),
    url(r'^queryUser$', views.queryUser, name='queryUser'),
    url(r'^delUser$', views.delUser, name='delUser'),
    url(r'^resetPw$', views.resetPw, name='resetPw'),
    url(r'^chargebackSerial$', views.chargebackSerial, name='chargebackSerial'),
    url(r'^checkUserId$', views.checkUserId, name='checkUserId'),
    url(r'^checkEditUserId$', views.checkEditUserId, name='checkEditUserId'),
    url(r'^checkCId$', views.checkCId, name='checkCId'),
    url(r'^checkEditCId$', views.checkEditCId, name='checkEditCId'),
    url(r'^systermLog$', views.systemLog, name='systemLog'),
    url(r'^addFixContent$',views.addFixContent,name='addFixContent'),
    url(r'^queryLog$',views.queryLog,name='queryLog'),
]

shande/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from super import urls as superurls
from ops import urls as opsurls
from sale import urls as saleurls
from customer import urls as customerurls
from teacher import urls as teacherurls
from bursar import urls as bursarurls
from wxqq import urls as wxqqurls
from trade import urls as tradeurls
from spot import urls as spoturls
from stock import urls as stockurls
from analyst import urls as analysturls
from shande.settings import STATIC_ROOT
urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # app super [default]
    url(r'', include(superurls, namespace="super")),

    # app ops
    url(r'^ops/', include(opsurls, namespace="ops")),

    # app sale
    url(r'^sale/', include(saleurls, namespace="sale")),

    # app customer
    url(r'^customer/', include(customerurls, namespace="customer")),

    # app teacher
    url(r'^teacher/', include(teacherurls, namespace="teacher")),

    # app bursar
    url(r'^bursar/', include(bursarurls, namespace="bursar")),

    # app wxqq
    url(r'^wxqq/', include(wxqqurls, namespace="wxqq")),

    # app trade
    url(r'^trade/', include(tradeurls, namespace="trade")),

    # app spot
    url(r'^spot/', include(spoturls, namespace="spot")),

    # app stock
    url(r'^stock/', include(stockurls, namespace="stock")),

    # app analyst
    url(r'^analyst/', include(analysturls, namespace="analyst")),
]
#
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG is False:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.UPLOAD_ROOT)
#     urlpatterns.append(url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),)

super/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from super import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^logoManage$', views.logoManage, name='logoManage'),
    url(r'^logoUpload$', views.logoUpload, name='logoUpload'),

    url(r'^accounts/login/$', views.login_view, name='login'),
    url(r'^accounts/logout/$', views.logout_view, name='logout'),

    url(r'^captcha$', views.captcha, name='captcha'),
    url(r'^siteswitch$', views.siteswitch, name='siteswitch'),
    url(r'^maintaince$', views.maintaince, name='maintaince'),
    url(r'^wap$', views.wap, name='wap'),

    url(r'^userInfo$', views.userInfo, name='userInfo'),
    url(r'^modifyPassword$', views.modifyPassword, name='modifyPassword'),

    url(r'^titleManage$', views.titleManage, name='titleManage'),
    url(r'^addTitle$', views.addTitle, name='addTitle'),
    url(r'^deleteTitle$', views.deleteTitle, name='deleteTitle'),

    url(r'^getTransmission$', views.getTransmission, name='getTransmission'),
    url(r'^demo$', views.demo, name='demo'),

     url(r'^newsPush$', views.newsPush, name='newsPush'),
]

super/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Title(models.Model):
    role_name = models.CharField(max_length=30, unique=True)
    role_desc = models.CharField(max_length=30, )

    def __str__(self):
        return self.role_name


class UserProfile (models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.CharField('公司', max_length=10, blank=True, null=True)
    commit = models.IntegerField('提交数', default=0)
    grade = models.IntegerField('有效客户数', default=0)
    department = models.CharField('部门', max_length=10, blank=True, null=True)
    group = models.CharField('组', max_length=10, default="", blank=True, null=True)
    cid = models.CharField('身份证号', max_length=18, blank=True, null=True)
    nick = models.CharField('真实姓名', max_length=10, blank=True, null=True)
    title = models.ForeignKey(Title, null=True, on_delete=models.SET_NULL)
    # "id","role_name","role_desc"
    # "1","admin","超级管理员"
    # "3","salemanager","客户开发经理"
    # "4","sale","客户开发专员"
    # "5","saleboss","客户开发总经理"
    # "6","teacher","客户管理专员"
    # "7","teachermanager","客户管理经理"
    # "8","teacherboss","客户管理总经理"
    # "9","bursar","财务专员"
    # "10","bursarmanager","财务经理"
    # "11","ops","管理员"
    # "12","spotteacher","现货老师"
    # "13","spotmanager","现货经理"
    # "14","analyst","技术分析师"
    failcount = models.IntegerField('失败次数', default=-1)
    faillocktime = models.DateTimeField('失败锁定时间', null=True)

    def __str__(self):
        return self.user.username

class UserCommitHis(models.Model):
    user = models.ForeignKey(User)
    day = models.DateField('修改时间', null=True)
    delta = models.IntegerField('变化量', default=0)
    total = models.IntegerField('总量', default=0)

    class Meta:
        unique_together = ("user", 'day')

class UserGradeHis(models.Model):
    user = models.ForeignKey(User)
    day = models.DateField('修改时间', null=True)
    delta = models.IntegerField('变化量', default=0)
    total = models.IntegerField('总量', default=0)

    class Meta:
        unique_together = ("user", 'day')

class Config(models.Model):
    key = models.CharField(max_length=30)
    value = models.CharField(max_length=300)

    def __str__(self):
        return self.key

class Transmission(models.Model):
    user = models.OneToOneField(User)
    transmission = models.CharField(max_length=300)
    checked = models.BooleanField(default=False)

super/views.py
# coding=utf-8
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from PIL import Image, ImageDraw, ImageFont
import os
import random
import string
try:
    from cStringIO import StringIO
except ImportError:
    from io import StringIO
import datetime
import traceback
import json

from shande.settings import BASE_DIR, UPLOAD_ROOT
from super.models import *
# from teacher.models import *
from trade.models import *
# from customer.models import *


# Create your views here.
def index(request):
    if request.user.is_authenticated():
        return render(request, 'super/index.html', locals())
    else:
        redirect_to = 'accounts/login/'
        return HttpResponseRedirect(redirect_to)

def login_view(request):
    data = {
        #"accept": request.META['HTTP_ACCEPT'],
    }
    failed = False
    if 'next' in request.GET:
        redirect_to = request.GET['next']
    else:
        redirect_to = '/ops/userManage/'
    if request.method == 'POST':
        if 'captcha' not in request.session:
            redirect_to = '/'
            return HttpResponseRedirect(redirect_to)
        if 'ident' in request.POST and string.upper(request.POST['ident']) == string.upper(request.session['captcha']):
            user = None
            try:
                user = User.objects.get(username=request.POST['username'])
            except Exception as e:
                print(e.__str__())
                print(request.POST['username'])
                error_msg = "用户  %s 不存在" % request.POST['username']
            if user:
                faillocktime = user.userprofile.faillocktime
                if faillocktime:
                    deltatime = (datetime.datetime.now() - faillocktime).total_seconds() - 900
                    if deltatime < 0:
                        error_msg = "用户已锁定，解锁倒计时 %s 秒" % int(deltatime)
                        return render(request, 'super/login_view.html', locals())
                userauth = authenticate(username=request.POST['username'], password=request.POST['password'])
                if userauth is not None:
                    login(request, userauth)
                    if userauth.userprofile.title.role_name in ['sale', 'saleboss', 'salemanager']:
                        # redirect_to = '/customer/customerManage'
                        redirect_to = '/'
                    elif userauth.userprofile.title.role_name in ['teacher', 'teacherboss', 'teachermanager']:
                        # redirect_to = '/customer/customerHandle'
                        redirect_to = '/'
                    elif userauth.userprofile.title.role_name in ['spotteacher', 'spotmanager']:
                        # redirect_to = '/spot/spotCustomer'
                        redirect_to = '/'
                    elif userauth.userprofile.title.role_name in ['bursar', 'bursarmanager']:
                        # redirect_to = '/customer/tradePayManage'
                        redirect_to = '/'
                    elif userauth.userprofile.title.role_name in ['admin', 'ops']:
                        # redirect_to = '/ops/userManage'
                        redirect_to = '/'
                    else:
                        redirect_to = '/'
                    userauth.userprofile.failcount = 0
                    userauth.userprofile.faillocktime = None
                    userauth.userprofile.save()
                    return HttpResponseRedirect(redirect_to)
                else:
                    failcount = user.userprofile.failcount
                    failcount += 1
                    if failcount > 3:
                        error_msg = "登陆失败超过三次，十五分钟内无法登陆"
                        user.userprofile.failcount = failcount
                        user.userprofile.faillocktime = datetime.datetime.now()
                    else:
                        error_msg = "用户密码错误，登陆失败三次后，将锁定十五分钟"
                        user.userprofile.failcount = failcount
                    user.userprofile.save()
            else:
                error_msg = "用户不存在"
        else:
            error_msg = "验证码错误"
    return render(request, 'super/login_view.html', locals())

def logout_view(request):
    logout(request)
    redirect_to = '/'
    return HttpResponseRedirect(redirect_to)

def captcha(request):
    image = Image.new('RGB', (147, 49), color=(255, 255, 255))
    # model, size, background color
    font_file = os.path.join(BASE_DIR, 'static/assets/fonts/simsun.ttc')
    font = ImageFont.truetype(font_file, 30)
    # the font object
    draw = ImageDraw.Draw(image)
    rand_str = ''.join(random.sample(string.letters + string.digits, 4))
    # The random string
    draw.text((7, 0), rand_str, fill=(0, 0, 0), font=font)
    # position, content, color, font
    del draw
    request.session['captcha'] = rand_str.lower()
    # store the content in Django's session store
    buf = StringIO()
    # a memory buffer used to store the generated image
    image.save(buf, 'jpeg')
    return HttpResponse(buf.getvalue(), 'image/jpeg')
    # return the image data stream as image/jpeg format, browser will treat it as an image

def siteswitch(request):
    maintaince = Config.objects.get(key="维护模式");
    return HttpResponse(maintaince.value)

def maintaince(request):
    message = Config.objects.get(key="维护公告")
    data = {
        "message": message.value,
    }
    return render(request, 'maintaince.html', data)

def wap(request):
    data = {
        "message": "手机网页暂时无法查看。",
    }
    return render(request, 'wap.html', data)

@login_required()
def userInfo(request):
    return render(request, 'super/userInfo.html', locals())

def modifyPassword(request):
    data = {}
    user = authenticate(username=request.user.username, password=request.POST['currentPassword'])
    if user is not None:
        user.set_password(request.POST['password'])
        try:
            user.save()
            logout(request)
            data['msg'] = "密码更新成功，请重新登陆"
            data['msgLevel'] = "info"
        except Exception as e:
            print(e.__str__)
            data['msg'] = "更新密码失败"
            data['msgLevel'] = "error"
    else:
        data['msg'] = "当前密码错误"
        data['msgLevel'] = "error"
    return HttpResponse(json.dumps(data))

@login_required()
def titleManage(request):
    if (request.user.userprofile.title.role_name != 'admin'):
        return HttpResponseRedirect("/")
    titles = Title.objects.all()
    data = {
        "titles": titles,
    }
    return render(request, 'super/titleManage.html', locals())

@login_required()
def addTitle(request):
    data = {}
    title = Title()
    title.role_name = request.POST['role_name']
    title.role_desc = request.POST['role_desc']
    try:
        title.save()
        data['msg'] = "新增职位成功"
        data['msgLevel'] = "info"
    except Exception as e:
        print(e.__str__())
        data['msg'] = "新增职位失败"
        data['msgLevel'] = "error"
    return HttpResponse(json.dumps(data))

@login_required()
def deleteTitle(request):
    data = {}
    titleId = request.POST['titleId']
    try:
        title = Title.objects.get(id=titleId)
        title.delete()
        data['msg'] = "删除职位成功"
        data['msgLevel'] = "info"
    except Exception as e:
        print(e.__str__)
        data['msg'] = "删除职位失败"
        data['msgLevel'] = "error"
    return HttpResponse(json.dumps(data))

@login_required()
def logoManage(request):
    if (request.user.userprofile.title.role_name != 'admin'):
        return HttpResponseRedirect("/")

    # trades = Trade.objects.all()
    # customers = Customer.objects.all()
    #
    # for customer in customers:
    #     customer.tradecount = trades.filter(customer_id=customer.id).count()
    #     customer.save()

    # # 修改密码
    # # users = User.objects.all()
    # # superprofile = UserProfile.objects.all()
    # # for user in superprofile:
    # #     if user.company == "T":
    # #         user.user.set_password("u000000")
    # #         user.user.save()
    #
    # teachers = Teacher.objects.all()
    # nums = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10']
    # for num in nums:
    #      for teacher in teachers:
    #         # 1组4部
    #         if teacher.teacherId == 'Z0104' + num:
    #             teacher.binduser.set_password('u000000')
    #             teacher.binduser.save()
    #             print(teacher.binduser.username)
    # nums = ['01', '02', '03', '04', '05', '06', '07', '08', '09']
    # for num in nums:
    #     for teacher in teachers:
    #         # 3组3部
    #         if teacher.teacherId == 'Z0303' + num:
    #             teacher.binduser.set_password('u000000')
    #             teacher.binduser.save()
    #             print(teacher.binduser.username)
    #         # 3组1部
    #         if teacher.teacherId == 'Z0301' + num:
    #             teacher.binduser.set_password('u000000')
    #             teacher.binduser.save()
    #             print(teacher.binduser.username)
    # nums = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11']
    # for num in nums:
    #     for teacher in teachers:
    #         # 2组2部
    #         if teacher.teacherId == 'Z0202' + num:
    #             teacher.binduser.set_password('u000000')
    #             teacher.binduser.save()
    #             print(teacher.binduser.username)

    return render(request, 'super/logoManage.html')

@login_required
def logoUpload(request):
    data = {}
    try:
        logofile = request.FILES['file']
        # file = open("super/static/super/images/header.jpg", "wb+")
        jpgfile = os.path.join(UPLOAD_ROOT, "super/images/header.jpg")
        #
        file = open(jpgfile, "wb+")

        for chunk in logofile.chunks():
            file.write(chunk)
        file.close()
        data['msg'] = "修改LOGO成功"

super/templates/super/index.html
{% extends 'base.html' %}

{% block title %}客户管理系统{% endblock %}
{% block content %}
{#     <div class="alert alert-success" style="text-align:center; position: relative ;width:500px;height:300px;top:10px;left:700px; background-color: inherit">#}
{##}
{#     </div>#}

    <div>
      <h1>
          <br/>
          <div class="alert alert-info" style="text-align:center">
              欢迎使用业务管理系统
          </div>
      </h1>

      {% if not request.user.is_authenticated %}

          <pre>请使用右上角的登陆按钮登陆管理系统</pre>
      {% endif %}
    </div>
{% endblock %}

super/templates/super/login_view.html
{% extends 'base.html' %}

{% block title %}login{% endblock %}
{% block content %}
{% if error_msg %}

{% endif %}

<div class="container" id="signinBox" >
{% if error_msg %}
<div class="alert alert-danger">{{ error_msg }}</div>
{% endif %}
<form class="form-horizontal" id="loginForm" action="/accounts/login/?next={{ redirect_to }}"
      method="post" autocomplete="on">
    <div class="form-group">
        <label for="username" class="col-sm-1 control-label">用户ID</label>
        <div class="col-sm-2">
            <input type="text" class="form-control" name="username" id="username" placeholder="用户名" autofocus="autofocus">
        </div>
        <label for="password" class="col-sm-1 control-label">密码</label>
        <div class="col-sm-2">
            <input type="password" class="form-control" name="password" id="password" placeholder="密码">
        </div>
        <label for="ident" class="col-sm-1 control-label">验证码</label>
        <div class="col-sm-2">
            <input type="text" class="form-control" name="ident" id="ident" placeholder="看不清？单击图片刷新" required>
        </div>
        <div class="col-sm-1">
            <img onclick="this.setAttribute('src', '/captcha?nocache='+Math.random());"
                src="{% url 'super:captcha' %}" alt="Captcha"/>
        </div>
        <div class="col-sm-2">
            <button type="submit" class="btn btn-primary btn-sm" id="loginButton">登录</button>

        </div>
    </div>
</form>
</div>

{% endblock %}

super/templates/super/logoManage.html
{% extends 'base.html' %}
{% block title %}logo管理{% endblock %}
{% block content %}
<form enctype="multipart/form-data">
    <div class="form-group">
        <div class="form-inline col-md-4">
             <input name="file" type="file"  class="btn btn-sm btn-default" required/>
        </div>
        <div class="form-inline col-md-4">
            <button type="button" class="btn btn-sm btn-primary" id="uploadLogo">上传</button>
        </div>
    </div>
</form>
<script type="text/javascript">
    $(function(){
        $('#uploadLogo').click(function(){
            var formData = new FormData($('form')[0]);
            $.ajax({
                url: "{% url 'super:logoUpload' %}",
                type: 'POST',
                dataType: 'json',
                success: function(result){
                    showMsgModal(result.msg, result.msgLevel);
                    if (result.msgLevel == 'info') {
                        setTimeout("window.location.reload()", 1500);
                    }
                },
                data: formData,
                cache: false,
                contentType: false,
                processData: false
            });
        });
    });
</script>
{% endblock %}

super/templates/super/titleManage.html
{% extends 'base.html' %}
{% block title %}职位列表{% endblock %}
{% block content %}

<form id="addTitleForm"
        class="form-inline" method="post" >
    <div class="form-inline">
        <div class="form-group col-md-4">
            <label for="role_name">职位名</label>
            <input type="text" class="form-control" name="role_name"
                data-bv-notempty="true"
                data-bv-notempty-message="不允许为空"/>
        </div>
        <div class="form-group col-md-4">
            <label for="role_desc">职位说明</label>
            <input type="text" class="form-control" name="role_desc"
                data-bv-notempty="true"
                data-bv-notempty-message="不允许为空"/>
        </div>
        <div class="form-group col-md-4">
            <button type="submit" class="btn btn-sm btn-primary">添加</button>
        </div>
    </div>
</form>
<br/><br/>
<table class="table-bordered table">
    {% if titles %}
        <thead class="bg-info">
            <tr>
                <td>id</td>
                <td>职位名称</td>
                <td>职位说明</td>
                <td>操作</td>
            </tr>
        </thead>
        <tbody>
        {% for title in titles %}
            <tr>
                <td>{{ title.id }}</td>
                <td>{{ title.role_name }}</td>
                <td>{{ title.role_desc }}</td>
                <td><button data-titleid="{{ title.id }}" onclick="deleteTitle(this)" class="btn btn-sm btn-danger">删除</button></td>
            </tr>
        {% endfor %}
        </tbody>
    {% else %}
        尚无职位名称
    {% endif %}
</table>
<script type="text/javascript">
$(function() {
    $('#addTitleForm').bootstrapValidator({
        excluded: [':disabled'],
        message: 'This value is not valid',
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        submitHandler: function (validator, form, submitButton) {
            $.post(
                "{% url 'super:addTitle' %}",
                form.serialize(),
                function(result) {
                    showMsgModal(result.msg, result.msgLevel);
                    if (result.msgLevel == 'info') {
                        setTimeout("window.location.reload()", 1500);
                    }
                },
                'json'
            );
        }
    });
});
</script>
<script type="text/javascript">
    function deleteTitle(obj){
        var titleId = $(obj).attr("data-titleid");
        $.post(
            "{% url 'super:deleteTitle' %}",
            {titleId:titleId},
            function(result) {
                showMsgModal(result.msg, result.msgLevel);
                setTimeout("window.location.reload()", 1500);
            },
            'json'
        )
    }
</script>
{% endblock %}

super/templates/super/userInfo.html
{% extends 'base.html' %}
{% block title %}用户信息{% endblock %}
{% block content %}

<ul class="nav nav-tabs">
    <li class="active">
        <a href="#userInfoTab" data-toggle="tab">用户信息</a>
    </li>
    <li class="">
        <a href="#modifyPassword" data-toggle="tab">修改密码</a>
    </li>
</ul>
<br/>
<div class="tab-content">
    <div class="tab-pane active" id="userInfoTab">
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <tr><td>用户名</td><td>{{ request.user }}</td></tr>
                <tr><td>隶属公司</td><td>{{ request.user.userprofile.company }}</td></tr>
                <tr><td>隶属部门</td><td>{{ request.user.userprofile.department }}</td></tr>
                <tr><td>职位</td><td>{{ request.user.userprofile.title.role_desc }}</td></tr>
                <tr><td>姓名</td><td>{{ request.user.userprofile.nick }}</td></tr>
                <tr><td>身份证</td><td>{{ request.user.userprofile.cid }}</td></tr>
            </table>
        </div>
    </div>
    <div class="tab-pane" id="modifyPassword">
        <form id="modifyPasswordForm" method="post" class="form-horizontal">
            <div class="form-group">
                <label class="col-md-offset-2 col-lg-2 col-md-2 control-label" for="currentPassword">旧密码</label>
                <div class="col-lg-5 col-md-5">
                    <input type="password" class="form-control" id="currentPassword" name="currentPassword"
                        data-bv-notempty="true"
                        data-bv-notempty-message="不允许为空"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-offset-2 col-lg-2 col-md-2 control-label" for="password" >新密码</label>
                <div class="col-lg-5 col-md-5">
                    <input type="password" class="form-control" id="password" name="password"
                        data-bv-notempty="true" data-bv-notempty-message="不允许为空"
                        data-bv-identical="true" data-bv-identical-field="passwordagain"
                        data-bv-identical-message="两次密码必须一致"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-offset-2 col-md-2 control-label" for="passwordagain" >确认新密码</label>
                <div class="col-md-5">
                    <input type="password" class="form-control" id="passwordagain" name="passwordagain"
                        data-bv-notempty="true" data-bv-notempty-message="不允许为空"
                        data-bv-identical="true" data-bv-identical-field="password"
                        data-bv-identical-message="两次密码必须一致"/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-4 col-md-6">
                    <button id="modifyPasswordBtn"
                        type="submit" class="btn btn-sm btn-primary">提交</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
$(function() {
    $('#modifyPasswordForm').bootstrapValidator({
        excluded: [':disabled'],
        message: 'This value is not valid',
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        submitHandler: function (validator, form, submitButton) {
            $.post(
                "{% url 'super:modifyPassword' %}",
                form.serialize(),
                function(result) {
                    showMsgModal(result.msg, result.msgLevel);
                    if (result.msgLevel == 'info') {
                        setTimeout("window.location.reload()", 1500);
                    }
                },
                'json'
            );
        }
    });
});
</script>
{% endblock %}